# Generated by Django 4.2.2 on 2023-06-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittlelemonAPI', '0002_menuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='book',
            name='Littlelemon_price_f5581b_idx',
        ),
        migrations.AddIndex(
            model_name='booker',
            index=models.Index(fields=['price'], name='Littlelemon_price_0b8faf_idx'),
        ),
    ]
