# Generated by Django 4.2.2 on 2023-06-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittlelemonAPI', '0007_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingUss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
