# Generated by Django 4.2.2 on 2023-06-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittlelemonAPI', '0008_ratinguss_delete_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratinguss',
            name='title',
            field=models.CharField(default='h', max_length=255),
        ),
    ]
