# Generated by Django 4.2.2 on 2023-06-20 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittlelemonAPI', '0010_ratinguss_menuitem_id_ratinguss_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratinguss',
            name='user',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ratinguss',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
