# Generated by Django 4.2.2 on 2023-06-20 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittlelemonAPI', '0013_alter_ratinguss_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratinguss',
            name='title',
        ),
    ]
